import React from "react";

const DisclaimerTraviazo = () => {
  return (
    <div className="py-16 px-6 max-w-5xl mx-auto text-center">
      {/* Main Heading */}
      <h2 className="text-2xl text-[#60ba30] font-bold mb-2">Traviazo</h2>
      <div className="w-20 h-1 bg-[#60ba30] mx-auto mb-4" />
      <h3 className="text-4xl text-[#263300] font-bold mb-12">
        Disclaimers Traviazo
      </h3>

      {/* Section 1 */}

      {/* Section 2 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          2. Definitions
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          SERVICE means the https://traviazo.com/ website operated by Traviazo.
          PERSONAL DATA means data about a living individual who can be
          identified from those data (or from those and other information either
          in our possession or likely to come into our possession). USAGE DATA
          is data collected automatically either generated by the use of Service
          or from Service infrastructure itself (for example, the duration of a
          page visit). COOKIES are small files stored on your device (computer
          or mobile device). DATA CONTROLLER means a natural or legal person who
          (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal data are,
          or are to be, processed. For the purpose of this Privacy Policy, we
          are a Data Controller of your data. DATA PROCESSORS (OR SERVICE
          PROVIDERS) means any natural or legal person who processes the data on
          behalf of the Data Controller. We may use the services of various
          Service Providers in order to process your data more effectively. DATA
          SUBJECT is any living individual who is the subject of Personal Data.
          THE USER is the individual using our Service. The User corresponds to
          the Data Subject, who is the subject of Personal Data.
        </p>
      </div>

      {/* Section 3 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          3. Information Collection and Use
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
      </div>

      {/* Section 4 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          4. Types of Data Collected
        </h3>
        <h3 className="text-2xl font-semibold text-black mb-2">
          Personal Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally, identifiable information
          may include, but is not limited to: Email address First name and last
          name Phone number Address, Country, State, Province, ZIP/Postal code,
          City Cookies and Usage Data We may use your Personal Data to contact
          you with newsletters, marketing or promotional materials and other
          information that may be of interest to you. You may opt out of
          receiving any, or all, of these communications from us by following
          the unsubscribe link.
        </p>
      </div>
      {/* Section 5 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          5. Use of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          Traviazo uses the collected data for various purposes: to provide and
          maintain our Service; to notify you about changes to our Service; to
          allow you to participate in interactive features of our Service when
          you choose to do so; to provide customer support; to gather analysis
          or valuable information so that we can improve our Service; to monitor
          the usage of our Service; to detect, prevent and address technical
          issues; to fulfil any other purpose for which you provide it; to carry
          out our obligations and enforce our rights arising from any contracts
          entered into between you and us, including for billing and collection;
          to provide you with notices about your account and/or subscription,
          including expiration and renewal notices, email-instructions, etc.; to
          provide you with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless you
          have opted not to receive such information; in any other way we may
          describe when you provide the information; for any other purpose with
          your consent.
        </p>
      </div>
      {/* Section 6 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          6. Retention of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies. We will also retain Usage Data for internal
          analysis purposes. Usage Data is generally retained for a shorter
          period, except when this data is used to strengthen the security or to
          improve the functionality of our Service, or we are legally obligated
          to retain this data for longer time periods.
        </p>
      </div>
      {/* Section 7 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          7. Transfer of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          Your information, including Personal Data, may be transferred to – and
          maintained on – computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction. If you are located
          outside United Kingdom and choose to provide information to us, please
          note that we transfer the data, including Personal Data, to United
          Kingdom and process it there. Your consent to this Privacy Policy
          followed by your submission of such information represents your
          agreement to that transfer. Traviazo will take all the steps
          reasonably necessary to ensure that your data is treated securely and
          in accordance with this Privacy Policy and no transfer of your
          Personal Data will take place to an organization or a country unless
          there are adequate controls in place including the security of your
          data and other personal information.
        </p>
      </div>
    </div>
  );
};

export default DisclaimerTraviazo;
