import React from "react";

const Privacytraviazo = () => {
  return (
    <div className="py-16 px-6 max-w-5xl mx-auto text-center">
      {/* Main Heading */}
      <h2 className="text-2xl text-[#60ba30] font-bold mb-2">Traviazo</h2>
      <div className="w-20 h-1 bg-[#60ba30] mx-auto mb-4" />
      <h3 className="text-4xl text-[#263300] font-bold mb-12">
        Privacy Policy Traviazo
      </h3>

      {/* Section 1 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          Effective date: 2024-11-08
        </h3>
        <h3 className="text-2xl font-semibold text-black mb-2">
          1. Introduction Welcome to Traviazo.
        </h3>
        <h3 className="text-xl font-semibold text-[#263300] mb-2">
          Welcome to Traviazo.
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          Traviazo (“us”, “we”, or “our”) operates https://traviazo.com/
          (hereinafter referred to as “Service”). Our Privacy Policy governs
          your visit to https://traviazo.com/, and explains how we collect,
          safeguard and disclose information that results from your use of our
          Service. We use your data to provide and improve Service. By using
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, the terms used in this Privacy Policy have the same meanings
          as in our Terms and Conditions. Our Terms and Conditions (“Terms”)
          govern all use of our Service and together with the Privacy Policy
          constitutes your agreement with us (“agreement”).
        </p>
      </div>

      {/* Section 2 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          2. Definitions
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          SERVICE means the https://traviazo.com/ website operated by Traviazo.
          PERSONAL DATA means data about a living individual who can be
          identified from those data (or from those and other information either
          in our possession or likely to come into our possession). USAGE DATA
          is data collected automatically either generated by the use of Service
          or from Service infrastructure itself (for example, the duration of a
          page visit). COOKIES are small files stored on your device (computer
          or mobile device). DATA CONTROLLER means a natural or legal person who
          (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal data are,
          or are to be, processed. For the purpose of this Privacy Policy, we
          are a Data Controller of your data. DATA PROCESSORS (OR SERVICE
          PROVIDERS) means any natural or legal person who processes the data on
          behalf of the Data Controller. We may use the services of various
          Service Providers in order to process your data more effectively. DATA
          SUBJECT is any living individual who is the subject of Personal Data.
          THE USER is the individual using our Service. The User corresponds to
          the Data Subject, who is the subject of Personal Data.
        </p>
      </div>

      {/* Section 3 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          3. Information Collection and Use
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
      </div>

      {/* Section 4 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          4. Types of Data Collected
        </h3>
        <h3 className="text-2xl font-semibold text-black mb-2">
          Personal Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally, identifiable information
          may include, but is not limited to: Email address First name and last
          name Phone number Address, Country, State, Province, ZIP/Postal code,
          City Cookies and Usage Data We may use your Personal Data to contact
          you with newsletters, marketing or promotional materials and other
          information that may be of interest to you. You may opt out of
          receiving any, or all, of these communications from us by following
          the unsubscribe link.
        </p>
      </div>
      {/* Section 5 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          5. Use of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          Traviazo uses the collected data for various purposes: to provide and
          maintain our Service; to notify you about changes to our Service; to
          allow you to participate in interactive features of our Service when
          you choose to do so; to provide customer support; to gather analysis
          or valuable information so that we can improve our Service; to monitor
          the usage of our Service; to detect, prevent and address technical
          issues; to fulfil any other purpose for which you provide it; to carry
          out our obligations and enforce our rights arising from any contracts
          entered into between you and us, including for billing and collection;
          to provide you with notices about your account and/or subscription,
          including expiration and renewal notices, email-instructions, etc.; to
          provide you with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless you
          have opted not to receive such information; in any other way we may
          describe when you provide the information; for any other purpose with
          your consent.
        </p>
      </div>
      {/* Section 6 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          6. Retention of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies. We will also retain Usage Data for internal
          analysis purposes. Usage Data is generally retained for a shorter
          period, except when this data is used to strengthen the security or to
          improve the functionality of our Service, or we are legally obligated
          to retain this data for longer time periods.
        </p>
      </div>
      {/* Section 7 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          7. Transfer of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          Your information, including Personal Data, may be transferred to – and
          maintained on – computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction. If you are located
          outside United Kingdom and choose to provide information to us, please
          note that we transfer the data, including Personal Data, to United
          Kingdom and process it there. Your consent to this Privacy Policy
          followed by your submission of such information represents your
          agreement to that transfer. Traviazo will take all the steps
          reasonably necessary to ensure that your data is treated securely and
          in accordance with this Privacy Policy and no transfer of your
          Personal Data will take place to an organization or a country unless
          there are adequate controls in place including the security of your
          data and other personal information.
        </p>
      </div>
      {/* Section 8 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          8. Disclosure of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          Business Transaction. If we or our subsidiaries are involved in a
          merger, acquisition or asset sale, your Personal Data may be
          transferred. Other cases. We may disclose your information also: to
          our subsidiaries and affiliates; to contractors, service providers,
          and other third parties we use to support our business; to fulfill the
          purpose for which you provide it; for the purpose of including your
          company’s logo on our website; for any other purpose disclosed by us
          when you provide the information; with your consent in any other
          cases; if we believe disclosure is necessary or appropriate to protect
          the rights, property, or safety of the Company, our customers, or
          others.
        </p>
      </div>
      {/* Section 9 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          9. Security of Data
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
      </div>
      {/* Section 10 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          10. Your Data Protection Rights Under General Data Protection
          Regulation (GDPR)
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          If you are a resident of the European Union (EU) and European Economic
          Area (EEA), you have certain data protection rights, covered by GDPR.
          We aim to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data. If you wish to be
          informed what Personal Data we hold about you and if you want it to be
          removed from our systems, please email us at info@traviazo.com. In
          certain circumstances, you have the following data protection rights:
          the right to access, update or to delete the information we have on
          you; the right of rectification. You have the right to have your
          information rectified if that information is inaccurate or incomplete;
          the right to object. You have the right to object to our processing of
          your Personal Data; the right of restriction. You have the right to
          request that we restrict the processing of your personal information;
          the right to data portability. You have the right to be provided with
          a copy of your Personal Data in a structured, machine-readable and
          commonly used format; the right to withdraw consent. You also have the
          right to withdraw your consent at any time where we rely on your
          consent to process your personal information; Please note that we may
          ask you to verify your identity before responding to such requests.
          Please note, we may not able to provide Service without some necessary
          data. You have the right to complain to a Data Protection Authority
          about our collection and use of your Personal Data. For more
          information, please contact your local data protection authority in
          the European Economic Area (EEA).
        </p>
      </div>
      {/* Section 11 */}
      <div className="mb-10">
        <h3 className="text-3xl font-semibold text-black mb-2">
          Our Policy on “Do Not Track” Signals:
        </h3>
        <p className="text-gray-700 text-base leading-relaxed">
          (CCPA) If you are a California resident, you are entitled to learn
          what data we collect about you, ask to delete your data and not to
          sell (share) it. To exercise your data protection rights, you can make
          certain requests and ask us: What personal information we have about
          you. If you make this request, we will return to you: The categories
          of personal information we have collected about you. The categories of
          sources from which we collect your personal information. The business
          or commercial purpose for collecting or selling your personal
          information. The categories of third parties with whom we share
          personal information. The specific pieces of personal information we
          have collected about you. A list of categories of personal information
          that we have sold, along with the category of any other company we
          sold it to. If we have not sold your personal information, we will
          inform you of that fact. A list of categories of personal information
          that we have disclosed for a business purpose, along with the category
          of any other company we shared it with. Please note, you are entitled
          to ask us to provide you with this information up to two times in a
          rolling twelve-month period. When you make this request, the
          information provided may be limited to the personal information we
          collected about you in the previous 12 months. To delete your personal
          information. If you make this request, we will delete the personal
          information we hold about you as of the date of your request from our
          records and direct any service providers to do the same. In some
          cases, deletion may be accomplished through de-identification of the
          information. If you choose to delete your personal information, you
          may not be able to use certain functions that require your personal
          information to operate. To stop selling your personal information. We
          don’t sell or rent your personal information to any third parties for
          any purpose. We do not sell your personal information for monetary
          consideration. However, under some circumstances, a transfer of
          personal information to a third party, or within our family of
          companies, without monetary consideration may be considered a “sale”
          under California law. You are the only owner of your Personal Data and
          can request disclosure or deletion at any time. If you submit a
          request to stop selling your personal information, we will stop making
          such transfers. Please note, if you ask us to delete or stop selling
          your data, it may impact your experience with us, and you may not be
          able to participate in certain programs or membership services which
          require the usage of your personal information to function. But in no
          circumstances, we will discriminate against you for exercising your
          rights. To exercise your California data protection rights described
          above, please send your request(s) by email: info@traviazo.com. Your
          data protection rights, described above, are covered by the CCPA,
          short for the California Consumer Privacy Act. To find out more, visit
          the official California Legislative Information website. The CCPA took
          effect on 01/01/2020. 13. Service Providers We may employ third party
          companies and individuals to facilitate our Service (“Service
          Providers”), provide Service on our behalf, perform Service-related
          services or assist us in analyzing how our Service is used. These
          third parties have access to your Personal Data only to perform these
          tasks on our behalf and are obligated not to disclose or use it for
          any other purpose.
        </p>
      </div>
    </div>
  );
};

export default Privacytraviazo;
